### ISSUE TITLE
Never write private styles to bohemia

### ISSUE THREAD

**Issue by subho007** [appknox/bohemia#3]
@dhilipsiva I see definition of styles https://github.com/appknox/bohemia/blob/master/base/_classes.sass#L198-L203 should belong privately to our frontend repo not something on an independent component like bohemia.

This also increases our time to release, because to change a localized style we, edit a public component `bohemia`

Please refactor it.

**Comment by dhilipsiva** [comment]
@subho007 Makes sense. I somehow missed it. Will Fix it in time.
